# Generated by Django 4.2.14 on 2024-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100, verbose_name='Order')),
                ('user', models.CharField(max_length=100, verbose_name='User')),
                ('payment_method', models.CharField(default='PAYPAL', max_length=100, verbose_name='Payment Method')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Is Paid ?')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['payment_method'], name='payment_pay_payment_7d17d2_idx')],
                'unique_together': {('order', 'payment_status')},
            },
        ),
    ]
